spring:
  application:
    name: ms-users
  datasource:
    url: jdbc:postgresql://192.168.88.13:5432/project_subscription
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    default-schema: users
server:
  port: 8083
