spring:
  application:
    name: ms-users
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  liquibase:
    default-schema: public
server:
  port: 8083
